### ISSUE TITLE
`get_issues': undefined method `code' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by victorhaggqvist** [nhmood/watson-ruby#250]
```
/home/victor/.rvm/gems/ruby-2.1.0/gems/watson-ruby-1.6.3/lib/watson/github.rb:328:in `get_issues': undefined method `code' for nil:NilClass (NoMethodError)
    from /home/victor/.rvm/gems/ruby-2.1.0/gems/watson-ruby-1.6.3/lib/watson/config.rb:206:in `run'
    from /home/victor/.rvm/gems/ruby-2.1.0/gems/watson-ruby-1.6.3/lib/watson/command.rb:172:in `execute'
    from /home/victor/.rvm/gems/ruby-2.1.0/gems/watson-ruby-1.6.3/bin/watson:11:in `<top (required)>'
    from /home/victor/.rvm/gems/ruby-2.1.0/bin/watson:23:in `load'
    from /home/victor/.rvm/gems/ruby-2.1.0/bin/watson:23:in `<main>'
```

**Comment by nhmood** [comment]
Looks like the HTTP call didn't return a proper response for some reason. Can you reproduce this problem? This isn't related to fixing this problem, I am just curious what the cause is.

I need to do actual exception handling around HTTP calls (among other things...) to prevent the whole app crashing on these types of things. Expect to see a fix for this soon.

**Comment by victorhaggqvist** [comment]
I have not been able to reproduce this, but I'm pretty sure it accured when I lost wifi connection in the middle of a github sync, which then obtiously timedout because of that.
