### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by rubenfonseca** [nhmood/watson-ruby#90]
Just installed watson and run for the first time.

OS X 10.9
Ruby 2.0-p195

Stacktrace:

```
/Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:230:in `match': invalid byte sequence in UTF-8 (ArgumentError)
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:230:in `match'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:230:in `block in parse_file'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:225:in `each'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:225:in `each_with_index'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:225:in `parse_file'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:126:in `block in parse_dir'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:96:in `each'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:96:in `parse_dir'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:50:in `block in run'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:49:in `each'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/parser.rb:49:in `run'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/lib/watson/command.rb:151:in `execute'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/gems/watson-ruby-1.0.1/bin/watson:18:in `<top (required)>'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/bin/watson:23:in `load'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/bin/watson:23:in `<main>'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in `eval'
  from /Users/rubenfonseca/.rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by nhmood** [comment]
I think this is the same problem as https://github.com/nhmood/watson-ruby/issues/89

**Comment by rubenfonseca** [comment]
I think so too. Closing this one, let's track #89. :)
